version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_DB=reservas_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: